version: "3.8"
volumes:
    db:
    backups:
networks:
    net:
        attachable: false
services:
    app:
        container_name: expanse_app
        image: ghcr.io/jc9108/expanse:latest
        working_dir: /app/
        volumes:
            - db:/app/backend/sqlite
            - backups:/app/backend/backups/
        networks:
            - net
        ports:
            - "1301:1301"
        environment:
            - VERSION=1.2.8
        env_file:
            - ./backend/.env_prod
        entrypoint: []
        command: sh -c "cd ./backend/ && npm run prod"
        restart: on-failure
