version: "3.8"
volumes:
    db:
        driver_opts:
            o: bind
            type: none
            device: ${PWD}/backend/sqlite
    backups:
        driver_opts:
            o: bind
            type: none
            device: ${PWD}/backend/backups
networks:
    net:
        attachable: false
services:
    app:
        container_name: expanse_app
        build: ./
        working_dir: /app/
        volumes:
            - db:/app/backend/sqlite
            - backups:/app/backend/backups/
        networks:
            - net
        ports:
            - "1301:1301"
        environment:
            - VERSION=1.2.8
        env_file:
            - ./backend/.env_prod
        entrypoint: []
        command: sh -c "cd ./backend/ && npm run prod"
        restart: on-failure
